### ISSUE TITLE
How to handle converting smplx to h5 files？

### ISSUE THREAD

**Issue by yangdaowu** [YoungSeng/FreeTalker#3]
Hello, I currently have an SMPLX file and I would like to convert it to an H5 file. Should I first convert it to BVH and then convert it according to the method you provided？

**Comment by YoungSeng** [comment]
No, our work converts the BVH of the BEAT dataset to smplx without reversing it; you can generate h5 files directly from the smplx format.

**Comment by yangdaowu** [comment]
Is it okay to skip Audio2Gesture directly and run Prepare features? May I know the file format after converting BVH to SMPLX? I will follow your converted file format. Thank you very much

**Comment by YoungSeng** [comment]
I think you can try both, or just read the well understood code and see if there's a specific part that's problematic

**Comment by yangdaowu** [comment]
Okay, I'll give it a try. Thank you for your answer
